exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: check-executables-have-shebangs
#    -   id: detect-aws-credentials
    -   id: detect-private-key

# -   repo: local
#     hooks:
#     -   id: check-test-coverage
#         name: Check test coverage is adequate
#         entry: make
#         args: [coverage]
#         language: system

-   repo: local
    hooks:
    -   id: check-security
        name: Check the security of code and dependencies
        entry: make
        args: [security]
        language: system

# -   repo: local
#     hooks:
#     -   id: check-linting
#         name: Check code style
#         entry: make
#         args: [lint]
#         language: system
