output-format: grouped
#output-format: vscode

strictness: veryhigh
doc-warnings: true
test-warnings: true
max-line-length: 140

frosted:
  run: false

pyroma:
  run: true

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - star-args
    - missing-docstring
pep8:
  full: true
  disable:
    - E126

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D205
    - D400
    - D401

#uses:
#  - flask
#  - celery

